;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                           ;
;                                  Keypad.INC                           	;
;                               Keypad Constants                            ;
;                                 Include File                              ;
;                                                                           ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the display functions
;
; Revision History:
;    11/02/2013			Created - Anjian Wu



; General Definitions

KEYEVENT        EQU     1               ; 
AUTO_REPEAT     EQU     8               ; 
DEBOUNCE_TARGET EQU     8               ; 