;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                         	;
;                                  Remote.INC                         		;
;                               Remote Constants                    	    ;
;                                 Include File                              ;
;                                                                           ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains robot constants
;
; Revision History:
;    12/12/2013			Created - Anjian Wu


; General Constants

PRESCALE            EQU     1000    ; How many Millisec per change in display
                                    ; status?
ACTION_LABEL       EQU     0       ;
SPEED_LABEL        EQU     2       ;
ANGLE_LABEL        EQU     4       ;
ERROR_LABEL        EQU     6       ;
